on:
  schedule:
    - cron: '30 3 * * 2,5'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run update script
      run: bash update-wishlist.sh
    - name: Update git stuff
      run: |
        git config --local user.name  ${{ github.actor }}
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto update"
    - name: push code to main
      run: git push origin HEAD:main
